version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm run audit fix --force
  build:
    commands:
      - ulimit -n 4096  # Increase file descriptor limit (adjust the number if needed)
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app)
