version: 0.2

phases:
  install:
    commands:
      - ulimit -n 4096  # Increase file descriptor limit
      - npm install --verbose
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app)
